name: Deploy SageMaker Templates Service Catalog

on:
  workflow_dispatch:
    inputs:
      deploymentName:
        description: 'Name of the deployment'
        required: true
        default: 'aiops'
      awsRegion:
        description: 'AWS Region for deployment'
        required: true
        default: 'us-east-1'
      action:
        description: 'Action to perform (deploy/destroy)'
        required: true
        type: choice
        options:
          - deploy
          - destroy
      awsAccountId:
        description: 'AWS Account ID'
        required: true
      adminRoleArn:
        description: 'Admin Role ARN'
        required: true
      awsAccessKeyId:
        description: 'AWS Access Key ID'
        required: true
      awsSecretAccessKey:
        description: 'AWS Secret Access Key'
        required: true
      awsSessionToken:
        description: 'AWS Session Token'
        required: true

jobs:
  deploy_sagemaker_templates:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.action == 'deploy' }}
    steps:
    - name: Clone AIOps Modules Repository
      run: |
        git clone --origin upstream --branch release/1.8.0 https://github.com/awslabs/aiops-modules
        cd aiops-modules
    
    - name: Setup Python Environment
      run: |
        cd aiops-modules
        python3 -m venv .venv && source .venv/bin/activate
        pip install -r ./requirements.txt
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ github.event.inputs.awsAccessKeyId }}
        aws-secret-access-key: ${{ github.event.inputs.awsSecretAccessKey }}
        aws-session-token: ${{ github.event.inputs.awsSessionToken }}
        aws-region: ${{ github.event.inputs.awsRegion }}
    
    - name: Set Environment Variables
      run: |
        cd aiops-modules
        echo "PRIMARY_ACCOUNT=${{ github.event.inputs.awsAccountId }}" >> $GITHUB_ENV
        echo "ADMIN_ROLE_ARN=${{ github.event.inputs.adminRoleArn }}" >> $GITHUB_ENV
    
    - name: Bootstrap CDK Environment
      run: |
        cd aiops-modules
        source .venv/bin/activate
        cdk bootstrap aws://${{ github.event.inputs.awsAccountId }}/${{ github.event.inputs.awsRegion }}
    
    - name: Bootstrap AWS Account for SeedFarmer
      run: |
        cd aiops-modules
        source .venv/bin/activate
        seedfarmer bootstrap toolchain --project ${{ github.event.inputs.deploymentName }} --trusted-principal ${{ github.event.inputs.adminRoleArn }} --as-target
    
    - name: Create Custom Manifest for SageMaker Templates
      run: |
        cd aiops-modules
        mkdir -p manifests/custom
        cat > manifests/custom/deployment.yaml << EOF
        name: ${{ github.event.inputs.deploymentName }}
        toolchain:
          region_mappings:
            - region: ${{ github.event.inputs.awsRegion }}
              account: ${{ github.event.inputs.awsAccountId }}
          modules: []
        groups:
          - name: sagemaker
            modules:
              - name: sagemaker-templates
                path: modules/sagemaker/sagemaker-templates-service-catalog
        EOF
    
    - name: Deploy Using SeedFarmer
      run: |
        cd aiops-modules
        source .venv/bin/activate
        seedfarmer apply manifests/custom/deployment.yaml

  destroy_sagemaker_templates:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.action == 'destroy' }}
    steps:
    - name: Clone AIOps Modules Repository
      run: |
        git clone --origin upstream --branch release/1.8.0 https://github.com/awslabs/aiops-modules
        cd aiops-modules
    
    - name: Setup Python Environment
      run: |
        cd aiops-modules
        python3 -m venv .venv && source .venv/bin/activate
        pip install -r ./requirements.txt
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ github.event.inputs.awsAccessKeyId }}
        aws-secret-access-key: ${{ github.event.inputs.awsSecretAccessKey }}
        aws-session-token: ${{ github.event.inputs.awsSessionToken }}
        aws-region: ${{ github.event.inputs.awsRegion }}
    
    - name: Destroy Using SeedFarmer
      run: |
        cd aiops-modules
        source .venv/bin/activate
        seedfarmer destroy ${{ github.event.inputs.deploymentName }}
